// <auto-generated />
using System;
using Admin.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Admin.Repository.Migrations
{
    [DbContext(typeof(AdminDBContext))]
    [Migration("20220223114005_AdminUser")]
    partial class AdminUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Admin.Models.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e7eafa-57e3-4a8b-84e1-75f8b256c863"),
                            CreatedAt = new DateTime(2022, 2, 23, 17, 10, 5, 672, DateTimeKind.Local).AddTicks(3723),
                            Password = "lg2YcG/GVJleM/MIIWmdlk0m0HhB1OtSOWGe12Fbx8zZEL4VMvjqRt3LRYgI2rarwT+jrH+mREaJ65oV0+WqPwMpX74=",
                            UpdatedAt = new DateTime(2022, 2, 23, 17, 10, 5, 672, DateTimeKind.Local).AddTicks(9866),
                            UserName = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
